server:
  port: 8085
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=notification_schema
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
