server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /v3/api-docs/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: ecommerceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /v3/api-docs/product-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**, /v3/api-docs/order-service/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**, /v3/api-docs/payment-service/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**, /v3/api-docs/notification-service/**
      discovery:
        locator:
          enabled: false # Explicit routes preferred
          lower-case-service-id: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, tracing

resilience4j.circuitbreaker:
  instances:
    ecommerceCircuitBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      registerHealthIndicator: true

resilience4j.retry:
  instances:
    ecommerceRetry:
      maxAttempts: 3
      waitDuration: 2000

spring.cloud.gateway.default-filters:
  - name: Retry
    args:
      retries: 3
      methods: GET,POST
      backoff:
        firstBackoff: 500ms
        maxBackoff: 2000ms
        factor: 2
        basedOnPreviousValue: false
