server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=order_schema
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring.cloud.openfeign.circuitbreaker.enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, tracing
